version: '3.8'

services:
  app:
    build:
      context: ../.. 
      dockerfile: infra/docker/Dockerfile 
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://user:password@db:5432/knowledge_base

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: knowledge_base
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: