services:
  app:
    build:
      context: ../.. 
      dockerfile: infra/docker/Dockerfile 
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
      - ../../.env.docker
    environment:
      - NODE_ENV=${NODE_ENV}

  db:
    image: postgres:latest
    restart: always
    env_file:
      - ../../.env.docker
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: